#!/bin/sh
ANTISCAN_DIR="/opt/etc/antiscan"
OLD_CONFIG_FILE="/opt/etc/ascn.conf"
CONFIG_FILE="$ANTISCAN_DIR/ascn.conf"
CRONTAB_FILE="$ANTISCAN_DIR/ascn_crontab.conf"
BOLD_TEXT="\033[1m"
NO_STYLE="\033[0m"
if [ -s "$OLD_CONFIG_FILE" ]; then
    if [ ! -d "$ANTISCAN_DIR" ]; then
        mkdir "$ANTISCAN_DIR"
    fi
    if cp -f "$OLD_CONFIG_FILE" "$CONFIG_FILE"; then
        printf "Имеющийся ascn.conf был перемещен в каталог ${BOLD_TEXT}/opt/etc/antiscan${NO_STYLE}\n"
    fi
fi
if [ -s "$CONFIG_FILE" ]; then
    rules_mask_str="$(grep "RULES_MASK" "$CONFIG_FILE")"
    save_ipsets_str="$(grep "SAVE_IPSETS" "$CONFIG_FILE")"
    ipset_save_path_old_str="$(grep "IPSETS_SAVE_PATH" "$CONFIG_FILE")"
    use_custom_exclude_str="$(grep "USE_CUSTOM_EXCLUDE_LIST" "$CONFIG_FILE")"
    custom_lists_block_mode_str="$(grep "CUSTOM_LISTS_BLOCK_MODE" "$CONFIG_FILE")"
    geoblock_mode_str="$(grep "GEOBLOCK_MODE" "$CONFIG_FILE")"
    geoblock_countries_str="$(grep "GEOBLOCK_COUNTRIES" "$CONFIG_FILE")"
    read_ndm_str="$(grep "READ_NDM_LOCKOUT_IPSETS" "$CONFIG_FILE")"
    ndm_lockout_time_str="$(grep "LOCKOUT_IPSET_BANTIME" "$CONFIG_FILE")"
    ports_forwarded_str="$(grep "PORTS_FORWARDED" "$CONFIG_FILE")"
    honeypot_ports_str="$(grep "HONEYPOT_PORTS" "$CONFIG_FILE")"
    honeypot_bantime_str="$(grep "HONEYPOT_BANTIME" "$CONFIG_FILE")"
    save_on_exit_str="$(grep "SAVE_ON_EXIT" "$CONFIG_FILE")"
    enable_ips_ban_str="$(grep "ENABLE_IPS_BAN" "$CONFIG_FILE")"
    enable_honeypot_str="$(grep "ENABLE_HONEYPOT" "$CONFIG_FILE")"
    geoexclude_countries_str="$(grep "GEO_EXCLUDE_COUNTRIES" "$CONFIG_FILE")"

    if [ -z "$rules_mask_str" ]; then
        sed -i '/^RECENT_CONNECTIONS_TIME=/iRULES_MASK=\"255.255.255.255\"' "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}RULES_MASK=\"255.255.255.255\"${NO_STYLE}\n"
    fi
    if [ -n "$ipset_save_path_old_str" ]; then
        sed -i 's/^IPSETS_SAVE_PATH/IPSETS_DIRECTORY/' "$CONFIG_FILE"
        printf "В имеющемся ascn.conf строка ${BOLD_TEXT}IPSETS_SAVE_PATH${NO_STYLE} заменена на ${BOLD_TEXT}IPSETS_DIRECTORY${NO_STYLE}\n"
    fi
    if [ -z "$(grep "IPSETS_DIRECTORY" "$CONFIG_FILE")" ]; then
        printf "\n\nIPSETS_DIRECTORY=\"\"\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}IPSETS_DIRECTORY=\"\"${NO_STYLE}\n"
    fi
    if [ -z "$save_ipsets_str" ]; then
        printf "\nSAVE_IPSETS=0\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}SAVE_IPSETS=0${NO_STYLE}\n"
    fi
    if [ -z "$use_custom_exclude_str" ]; then
        printf "\nUSE_CUSTOM_EXCLUDE_LIST=0\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}USE_CUSTOM_EXCLUDE_LIST=0${NO_STYLE}\n"
    fi
    if [ -z "$custom_lists_block_mode_str" ]; then
        printf "CUSTOM_LISTS_BLOCK_MODE=0\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}CUSTOM_LISTS_BLOCK_MODE=0${NO_STYLE}\n"
    fi
    if [ -z "$geoblock_mode_str" ]; then
        printf "GEOBLOCK_MODE=0\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}GEOBLOCK_MODE=0${NO_STYLE}\n"
    fi
    if [ -z "$geoblock_countries_str" ]; then
        printf "GEOBLOCK_COUNTRIES=\"\"\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}GEOBLOCK_COUNTRIES=\"\"${NO_STYLE}\n"
    fi
    if [ -z "$read_ndm_str" ]; then
        printf "\nREAD_NDM_LOCKOUT_IPSETS=0\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}READ_NDM_LOCKOUT_IPSETS=0${NO_STYLE}\n"
    fi
    if [ -z "$ndm_lockout_time_str" ]; then
        printf "LOCKOUT_IPSET_BANTIME=864000\n" >>"$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}LOCKOUT_IPSET_BANTIME=864000${NO_STYLE}\n"
    fi
    if [ -z "$ports_forwarded_str" ]; then
        source "$CONFIG_FILE"
        sed -i "/^PORTS=/aPORTS_FORWARDED=\"$PORTS\"" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}PORTS_FORWARDED${NO_STYLE}\n"
    fi
    if [ -z "$honeypot_ports_str" ]; then
        sed -i "/^PORTS_FORWARDED=/aHONEYPOT_PORTS=\"\"" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}HONEYPOT_PORTS=\"\"${NO_STYLE}\n"
    fi
    if [ -z "$honeypot_bantime_str" ]; then
        sed -i "/^HONEYPOT_PORTS=/aHONEYPOT_BANTIME=864000" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}HONEYPOT_BANTIME=864000${NO_STYLE}\n"
    fi
    if [ -z "$save_on_exit_str" ]; then
        sed -i "/^SAVE_IPSETS=/aSAVE_ON_EXIT=0" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}SAVE_ON_EXIT=0${NO_STYLE}\n"
    fi
    if [ -z "$enable_honeypot_str" ]; then
        source "$CONFIG_FILE"
        honeypot_var=""
        [ -z "$HONEYPOT_PORTS" ] && honeypot_var="ENABLE_HONEYPOT=0" || honeypot_var="ENABLE_HONEYPOT=1"
        sed -i "/^PORTS_FORWARDED=/a${honeypot_var}" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}${honeypot_var}${NO_STYLE}\n"
    fi
    if [ -z "$enable_ips_ban_str" ]; then
        sed -i "/^HONEYPOT_BANTIME=/aENABLE_IPS_BAN=1" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}ENABLE_IPS_BAN=1${NO_STYLE}\n"
    fi
    if [ -z "$geoexclude_countries_str" ]; then
        sed -i "/^GEOBLOCK_COUNTRIES=/aGEO_EXCLUDE_COUNTRIES=\"\"" "$CONFIG_FILE"
        printf "В имеющийся ascn.conf добавлена новая строка ${BOLD_TEXT}GEO_EXCLUDE_COUNTRIES=\"\"${NO_STYLE}\n"
    fi
fi
if [ -s "$CRONTAB_FILE" ]; then
    read_ndm_task_str="$(grep 'read_ndm_ipsets' "$CRONTAB_FILE")"
    if [ -z "$read_ndm_task_str" ]; then
        printf "\n*/2 * * * * /opt/etc/init.d/S99ascn read_ndm_ipsets &\n" >>"$CRONTAB_FILE"
        sed -n -i '\:S99ascn:p' "$CRONTAB_FILE"
        printf "В имеющийся ascn_crontab.conf добавлена задача для чтения списков NDM ip lockout-policy\n"
    fi
fi
